MODEL:
  TYPE: lit
  NAME: lit_base
  DROP_PATH_RATE: 0.5
  OFFSET_LR_MULTI: 0.01
  LIT:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 128
  DATA_PATH: /data1/downloads/datasets/imagenet
  DATASET: imagenet